name: PlaySID CI

on:
  push:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

  schedule:
    - cron: '00 12 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    container: trixitron/m68k-amigaos-gcc

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Trust git workdir
      run: git config --global --add safe.directory $PWD

    - name: Clean
      run: make clean

    - name: Build
      run: make
