name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: trixitron/m68k-amigaos-gcc

    steps:
    - uses: actions/checkout@v3

    - name: Clean
      run: make clean

    - name: Build
      run: make
